tanmer-account/config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper do
    controllers applications: 'apps'
  end

  devise_for :users, skip: [:sessions, :password, :registrations, :unlocks],
    controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }

  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  if ENV['ENABLE_REGISTERATION'] == 'true'
    get :sign_up, to: 'registrations#new'
    post :sign_up, to: 'registrations#create'
  end
  get :logout, to: 'sessions#destroy'
  get 'sessions/status', to: 'sessions#status'
  get 'sessions/get-token', to: 'sessions#get_token'
  post 'sessions/sms-auth-code', to: 'sessions#sms_auth_code_for_login'
  post 'sessions/sms-auth', to: 'sessions#sms_auth_for_login'
  post 'registrations/sms-auth-code', to: 'registrations#sms_auth_code_for_register'
  post 'registrations/sms-auth', to: 'registrations#sms_auth_for_register'

  post 'login-with-token', to: 'sessions#create_with_token' # this route is a example for Application Client

  resources :users
  resources :roles
  resource :profile
  resources :tokens
  resource :system_settings, only: [:show]

  root to: 'home#index'
  get :healthz, to: 'home#healthz'
  get 'pages/agreement'
  get 'pages/privacy'

  namespace :api do
    namespace :v1 do
      resource :users, only: [] do
        get :profile
      end

      resources :permissions, except: [:new, :edit]
      scope :auth, controller: 'auth', as: :auth do
        # post :with_token
        # auth from "HTTP_AUTHORIZATION"=>"Basic bWVAemhhbmd4aC5uZXQ6bXlwYXNz"
        #   it includes username and api token
        get :http_digest
      end
    end
  end
end

tanmer-account/app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  skip_authorization_check
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  def index
    @tokens = current_user.tokens
  end

  def show
  end

  def new
    @token = current_user.tokens.new
  end

  def edit
  end

  def create
    h = token_params
    data = {
      name: h[:name],
      scopes: 'public api'
    }
    data[:expires_in] = h[:expires_at] && (h[:expires_at] - Time.now).ceil
    @token = current_user.tokens.new(data)

    respond_to do |format|
      if @token.save
        format.html { redirect_to token_path(@token), notice: 'Token创建成功.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    h = token_params
    data = {
      name: h[:name],
      scopes: 'public api'
    }
    data[:expires_in] = h[:expires_at] && (h[:expires_at] - @token.created_at).ceil
    respond_to do |format|
      if @token.update(data)
        format.html { redirect_to token_path(@token), notice: 'Token更新成功.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_path, notice: 'Token删除成功.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = current_user.tokens.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      h = params.require(:token)
      {
        name: h[:name],
        expires_at: h[:no_expires] ? nil : Time.parse("#{h['expires_at(1i)']}-#{h['expires_at(2i)']}-#{h['expires_at(3i)']} #{h['expires_at(4i)']}:#{h['expires_at(5i)']}")
      }
    end
end

tanmer-account/app/views/tokens/_form.html.slim
= simple_form_for @token, as: :token, url: @token.new_record? ? tokens_path : token_path(@token) do |f|
  - if @token.errors.any?
      .bs-callout.bs-callout-danger
        h2 = "#{pluralize(@token.errors.count, "error")} prohibited this user from being saved:"
        ul
          - @token.errors.full_messages.each do |message|
            li = message
  
  = f.input :name
  = f.input :expires_at, as: :datetime
  .form-group
    = f.button :submit, class: 'btn btn-primary'
    =< link_to 'Show', token_path(@token), class: 'btn btn-default' if @token.persisted?
    =< link_to "Back", back_link, class: 'btn btn-default' if defined? back_link

tanmer-account/app/views/tokens/edit.html.slim
.page-header
  h1
    | 更新Token

== render 'form', back_link: tokens_path

tanmer-account/app/views/tokens/index.html.slim
.page-header
  h1
    | Token列表
    = link_to '新建', new_token_path, class: 'btn btn-success pull-right'

table.table
  thead
    tr
      th 名字
      th Token
      th 过期时间
      th

  tbody
    - @tokens.each do |token|
      tr
        td = token.name
        td = token.token
        td = token.expires_in.blank? ? '永久' : (time_ago_in_words(token.expires_at) + (token.expires_at > Time.now ? '后': '前'))
        td
          => link_to 'Show', token_path(token), class: 'btn btn-default'
          => link_to 'Edit', edit_token_path(token), class: 'btn btn-default'
          => link_to 'Destroy', token_path(token), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

tanmer-account/app/views/tokens/new.html.slim
.page-header
  h1
    | 新增Token

== render 'form', back_link: tokens_path

tanmer-account/app/views/tokens/show.html.slim
p#notice = notice

p
  strong Name:
  = @token.name
p
  strong Token:
  = @token.token
p
  strong 过期时间:
  = @token.expires_at.to_s(:local)

= link_to 'Edit', edit_token_path(@token)
'  |
= link_to 'Back', tokens_path